name: Publish DockerHub

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Greeting heroku world
        run: echo "hello heroku world"
