name: Build and Publish to the DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        run: echo "hello heroku world"
